version: "3"

services:
  indi_base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indi_base
    env_file: .env


  mariadb_indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mariadb
    env_file: .env
    volumes:
      - database_indi_allsky:/var/lib/mysql
    #ports:
    #  - "13306:3306"


  indiserver_indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indiserver
    env_file: .env
    depends_on:
      - indi_base
    privileged: true
    ports:
      - "17624:7624"


  indi_allsky_base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indi_allsky_base
    env_file: .env
    depends_on:
      - indi_base
    volumes:
      - images_indi_allsky:/var/www/html/allsky


  gunicorn_indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gunicorn
    env_file: .env
    depends_on:
      - mariadb_indi_allsky
      - indi_allsky_base
    volumes:
      - images_indi_allsky:/var/www/html/allsky
      - migrations_indi_allsky:/var/lib/indi-allsky
    #ports:
    #  - "8000:8000"


  capture_indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.capture
    env_file: .env
    depends_on:
      - mariadb_indi_allsky
      - indiserver_indi_allsky
      - indi_allsky_base
    volumes:
      - images_indi_allsky:/var/www/html/allsky


  nginx_indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
    env_file: .env
    depends_on:
      - gunicorn_indi_allsky
    volumes:
      - images_indi_allsky:/var/www/html/allsky
    ports:
      - "8080:80"
      - "8443:443"


  mosquitto_indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mosquitto
      args:
        - MOSQUITTO_USER=${INDIALLSKY_MOSQUITTO_USER}
        - MOSQUITTO_PASS=${INDIALLSKY_MOSQUITTO_PASS}
    env_file: .env
    volumes:
      - mosquitto_data_indi_allsky:/mosquitto/data
    ports:
      - "18883:8883"
      - "18081:8081"


volumes:
  database_indi_allsky:
  migrations_indi_allsky:
  images_indi_allsky:
  mosquitto_data_indi_allsky:

