version: "3"

services:
  indi_base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indi_base_ubuntu
    env_file: .env

  indiserver:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indiserver
    env_file: .env
    privileged: true
    ports:
      - "17624:7624"

  indi_allsky_base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indi_allsky_base
    env_file: .env
    volumes:
      - database:/var/lib/indi-allsky
      - images:/var/www/html/allsky

  gunicorn_indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gunicorn
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - database:/var/lib/indi-allsky
      - images:/var/www/html/allsky

  indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indi_allsky
    env_file: .env
    volumes:
      - database:/var/lib/indi-allsky
      - images:/var/www/html/allsky

  nginx_indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
    depends_on:
      - gunicorn_indi_allsky
    env_file: .env
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - images:/var/www/html/allsky


volumes:
  database:
  images:

