version: "3"

services:
  indi_base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indi_base_ubuntu
    env_file: .env

  indiserver:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indiserver
    env_file: .env
    privileged: true
    #ports:
    #  - "17624:7624"

  indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indi_allsky
    depends_on:
      - indiserver
    env_file: .env
    volumes:
      - config:/etc/indi-allsky
      - database:/var/lib/indi-allsky
      - images:/var/www/html/allsky

  gunicorn_indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gunicorn
    depends_on:
      - indi_allsky
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - config:/etc/indi-allsky
      - database:/var/lib/indi-allsky
      - /var/www/html/allsky

  nginx_indi_allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
    depends_on:
      - indi_allsky
    env_file: .env
    ports:
      - "8443:443"
    volumes:
      - config:/etc/indi-allsky
      - images:/var/www/html/allsky


volumes:
  config:
  database:
  images:

