---
blocking_packages:
  - indi-full
  - libindi-data
  - libindi-dev
  - libindi-plugins
common_packages:
  - python3-apt
indi_packages:
  - build-essential
  - libnova-dev
  - libcfitsio-dev
  - libusb-1.0-0-dev
  - zlib1g-dev
  - libgsl-dev
  - cmake
  - git
  - libjpeg-dev
  - libcurl4-gnutls-dev
  - libtheora-dev
  - libfftw3-dev
  - pkg-config
  - libgmock-dev
  - libev-dev
indi_3rdparty_packages:
  - build-essential
  - libnova-dev
  - libcfitsio-dev
  - libusb-1.0-0-dev
  - zlib1g-dev
  - libgsl-dev
  - cmake
  - git
  - libjpeg-dev
  - libcurl4-gnutls-dev
  - libtiff-dev
  - libfftw3-dev
  - libftdi-dev
  - libgps-dev
  - libraw-dev
  - libdc1394-dev
  - libgphoto2-dev
  - libboost-dev
  - libboost-regex-dev
  - librtlsdr-dev
  - liblimesuite-dev
  - libftdi1-dev
  - libavcodec-dev
  - libavdevice-dev
  - libnutclient-dev
  - pkg-config
  - fxload
