version: "3"

services:
  indi_allsky:
    build:
      context: .
      dockerfile: Dockerfile.indi_allsky
    env_file: env.local

  indiserver:
    build:
      context: ..
      dockerfile: Dockerfile.indiserver
    env_file: env.local
    #ports:
    #  - "17624:7624"

  capture:
    build:
      context: .
      dockerfile: Dockerfile.capture
    depends_on:
      - indiserver
    env_file: env.local
    volumes:
      - /etc/indi-allsky
      - /var/lib/indi-allsky
      - /var/www/html/allsky

  #gunicorn:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.gunicorn
  #  depends_on:
  #    - indi_allsky
  #  env_file: env.local
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - /etc/indi-allsky
  #    - /var/lib/indi-allsky
  #    - /var/www/html/allsky

  #apache:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.apache
  #  depends_on:
  #    - indi_allsky
  #  env_file: env.local
  #  ports:
  #    - "8443:443"
  #  volumes:
  #    - /etc/indi-allsky
  #    - /var/lib/indi-allsky
  #    - /var/www/html/allsky
