version: "3"

services:
  indi_allsky:
    build:
      context: .
      dockerfile: Dockerfile.indi_allsky
    env_file: env.local

  indiserver:
    build:
      context: ..
      dockerfile: Dockerfile.indiserver
    env_file: env.local
    #ports:
    #  - "17624:7624"

  capture:
    build:
      context: .
      dockerfile: Dockerfile.capture
    depends_on:
      - indiserver
    env_file: env.local
    volumes:
      - config:/etc/indi-allsky
      - database:/var/lib/indi-allsky
      - images:/var/www/html/allsky

  #app:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.gunicorn
  #  depends_on:
  #    - capture
  #  env_file: env.local
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - config:/etc/indi-allsky
  #    - database:/var/lib/indi-allsky
  #    - /var/www/html/allsky

  #web:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.nginx
  #  depends_on:
  #    - capture
  #  env_file: env.local
  #  ports:
  #    - "8443:443"
  #  volumes:
  #    - config:/etc/indi-allsky
  #    - images:/var/www/html/allsky


volumes:
  config:
  database:
  images:

